### ISSUE TITLE
[Bug] rife models new update got bug.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vsrepo#181]
environment:

Windows 10 21H2 x64
vapoursynth R58-RC2
python 3.10.4

some code like:

https://github.com/vapoursynth/vsrepo/commit/0d274bbab142d408e220c5ac63cba39fe89109a7

```
					"models/rife-v2.3": [
						"models/rife-v2.3",
						"79ff2fac182203007ebabe782d5a1727f92516909e923b3e1ca2d61c8322765c"
					],
```

will create a file called rife-v2.3 and makes error.

```
vsrepo.py upgrade-all
Rebuilding dist-info dirs for other python package installers
Fetching: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/releases/download/r3/RIFE-models.7z
Traceback (most recent call last):
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 941, in <module>
    inst = upgrade_all_packages(args.force)
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 698, in upgrade_all_packages
    res = upgrade_files(pkg)
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 668, in upgrade_files
    res = install_package(dep)
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 655, in install_package
    fres = install_files(p)
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 627, in install_files
    os.makedirs(os.path.join(dest_path, os.path.split(install_fn)[0]), exist_ok=True)
  File "C:\Program Files\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\Administrator\\AppData\\Roaming\\VapourSynth\\plugins64\\models/rife-v2.3'
```

**Comment by theChaosCoder** [comment]
Thx should be good now.

**Comment by theChaosCoder** [comment]
But I noticed that this "big" packages takes over 5min to install on a nvme 3gb/s :-/
