### ISSUE TITLE
pip throwing warnings for certain plugins

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vsrepo#199]
This has been an issue for a while now, but pip will continually warn the user about certain plugins installed through vsrepo.
![image](https://user-images.githubusercontent.com/42927908/221465533-73567556-4b04-4031-a2c8-e6f18d18c8df.png)

This seems to crop up for any plugin that has a `_-_` in the directory name:

* `CAS_-_Contrast_Adaptive_Sharpening-2.dist-info`
* `vfx_-_Special_Effects-2021.10.31.dist-info`

But it doesn't care if it's just a `_` or `-`:

* `Bilateral-3.dist-info`
* `D2V_Source-1.2.dist-info`
* `MVTools__float-9.dist-info`

My suggestion would be to replace `_-_` with either `_` or `-`, if that is possible.

**Comment by theChaosCoder** [comment]
Please check if pip is happy now

**Comment by seproDev** [comment]
For [vapoursynth-zip](https://github.com/dnjulek/vapoursynth-zip) pip is still not happy.

The stub is generated at `vapoursynth-zip-5.dist-info`. This actually causes `pip list --outdated` to crash:
```
> pip list --outdated
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\list.py", line 199, in run
    packages = self.get_outdated(packages, options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\list.py", line 212, in get_outdated
    if dist.latest_version > dist.version
                             ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 174, in version
    return parse_version(version)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: {version!r}")
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'zip-5'
```
