### ISSUE TITLE
Eedi3m install error

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#20]
python .\vsrepo.py -p install EEDI3m
```
Fetching: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3/releases/download/r3/EEDI3-r3.7z
Traceback (most recent call last):
  File ".\vsrepo.py", line 307, in <module>
    result = install_package(name) or result
  File ".\vsrepo.py", line 272, in install_package
    install_files(p)
  File ".\vsrepo.py", line 245, in install_files
    ref_digest = p['releases'][0][bin_name]['hash'][stripped_fn]
KeyError: 'EEDI3m.dll'
```

**Comment by myrsloik** [comment]
Fixed, forgot to rename it everywhere
