### ISSUE TITLE
DLLs failed to load - "GetLastError() returned 126"

### ISSUE THREAD

**Issue by TezuSubs** [vapoursynth/vsrepo#214]
```
Rebuilding dist-info dirs for other python package installers
Updating VapourSynth stubs
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\Bilateral.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\BilateralGPU_RTC.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\bm3dcuda_rtc.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\bm3dhip.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\DePan.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\pi_win_proxy_loaderd.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\realcugannv.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\vctrans.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Failed to load C:\Users\Tezu\AppData\Roaming\VapourSynth\plugins64\vs_it.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
Nothing done
```
I have confirmed that all of the files are physically installed at the location.
running `vsrepo.py installed` shows that all available packages, other than `FrameRateConverter v2.0-beta`, and `TNLMeans git:22a40af` are installed, both of which fail to download if attempting to install them again. (attempting to uninstall some of them gives a not found error)

This is on a fresh install of R65 on Windows10, using admin CMD.
on local CMD and additional errors show.
```
Traceback (most recent call last):
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 888, in <module>
    update_genstubs()
  File "C:\Program Files\VapourSynth\vsrepo\vsrepo.py", line 804, in update_genstubs
    genstubs4([])
  File "C:\Program Files\VapourSynth\vsrepo\vsgenstubs4\init.py", line 609, in main
    output_stubs(args, cores, list(implementations), list(instances))
  File "C:\Program Files\VapourSynth\vsrepo\vsgenstubs4\init.py", line 510, in output_stubs
    stubs_path = locate_or_create_stub_file()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\VapourSynth\vsrepo\vsgenstubs4\init.py", line 431, in locate_or_create_stub_file
    with open(join_path(site_package_dir, iname, 'RECORD'), 'a+', newline='') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python\\Lib\\site-packages\\VapourSynth-65.dist-info\\RECORD'
```

**Comment by theChaosCoder** [comment]
You are probably missing some runtimes. For example Bilateral.dll & vs_it.dll both depends on MSVCR120.dll. I think you need Visual C++ Redistributables 2013 for that:  https://www.microsoft.com/en-us/download/details.aspx?id=40784

Alternative: install an All I One Pack with every runtime https://github.com/abbodi1406/vcredist

bm3dhip needs some amd gpu runtimess (amdhip64.dll), if you don't have a amd gpu the plugin won't work anyway.

**Comment by TezuSubs** [comment]
Installing the all-in-one removed `Bilateral.dll`, `vctrans.dll` and `vs_it.dll` from the error list, and uninstalled dhip since I don't have any PCIe GPU installed.
