### ISSUE TITLE
portable R66 and vsrupdate.py aborts with https error when processing file: `local\eedi2.json`

### ISSUE THREAD

**Issue by hydra3333** [vapoursynth/vsrepo#219]
Hello with vapoursynth portable R66 and vsrupdate.py this
`"G:\TEST\Vapoursynth-x64\python.exe" "G:\TEST\Vapoursynth-x64\vsrupdate.py" update-local -o -g some_key`
eventually fails like this:
```
Fetching: https://api.github.com/repos/sekrit-twc/EdgeFixer/releases
Release file already up to date
Only github and pypi projects supported, edi_rpow2 not scanned
Fetching: https://api.github.com/repos/HomeOfVapourSynthEvolution/VapourSynth-EEDI2/releases
Release file already up to date
Traceback (most recent call last):
  File "G:\TEST\Vapoursynth-x64\vsrupdate.py", line 474, in <module>
    result = update_package(os.path.splitext(os.path.basename(f))[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TEST\Vapoursynth-x64\vsrupdate.py", line 291, in update_package
    apifile = json.loads(fetch_url(get_git_api_url(pfile['github']) or "", pfile['name'], token=args.git_token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TEST\Vapoursynth-x64\vsrupdate.py", line 112, in fetch_url
    with urllib.request.urlopen(req) as urlreq:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.py", line 215, in urlopen
  File "urllib\request.py", line 521, in open
  File "urllib\request.py", line 630, in http_response
  File "urllib\request.py", line 559, in error
  File "urllib\request.py", line 492, in _call_chain
  File "urllib\request.py", line 639, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
after processing file: `local\eedi2.json`
and attempting to process file: `local\eedi2cuda.json`

Deleting file `local\eedi2cuda.json` just before the vsrupdate makes it all work :)

Cheers

**Comment by theChaosCoder** [comment]
The git repo does not exist anymore. I deleted it locally but forgot to commit ^_^"
