### ISSUE TITLE
Invalid version identifiers and names starting with pip 24.x?

### ISSUE THREAD

**Issue by Vodes** [vapoursynth/vsrepo#235]
This has come up a few times on the JET server and even in my DMs so I thought it'd be best to make an issue now.

Starting with pip 24.2 (or 24.3, not sure), proper version identifiers and names for python package metadata have been enforced.
This results in an actual error when doing anything with pip and should be addressed ASAP.

Doesn't seem to be affecting all plugins but it might be a good idea to rethink how the metadata gets generated in general.

<details>
<summary>One such error</summary>

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 167, in version
    return parse_version(version)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'Reader__IMWRI-2'
WARNING: Error parsing dependencies of imagemagick-writer: Invalid version: 'Reader__IMWRI-2'
```

</details>

**Comment by Vodes** [comment]
Actually somewhat urgent as it's more likely to have an updated pip version as time goes on 🙂

**Comment by theChaosCoder** [comment]
How would a fix look like? Replace all **-** with **_** ?

**Comment by Vodes** [comment]
Looking at https://peps.python.org/pep-0440/ that wouldn't be valid either.
Also just noticed there's some pep440 regex stuff already in the code so I'm not even sure how stuff like this ends up in there
![image](https://github.com/user-attachments/assets/42a4ceb7-a141-4064-b7eb-3664e68a6264)

**Comment by theChaosCoder** [comment]
get_python_package_name() is responsible for the python package name

But how to trigger the error? I'm on pip 24.3.1 and everything is fine for me.

**Comment by Vodes** [comment]
I don't have a system with vsrepo on hand but last time I had the issue you'd always get that when trying to install something via pip.

**Comment by theChaosCoder** [comment]
I know there were problems before for a pattern like _-_ 
I fixed it months ago with a simple replace("_-_", "_")

The errors could be leftovers from older vsrepo installations. Removing the problematic *.dist-info folders should fix it I hope :D

**Comment by Ichunjo** [comment]
```
× Cannot process installed package vapoursynth-zip 5 in 'c:\\users\\varde\\appdata\\roaming\\python\\python312\\site-packages' because it has an invalid version:
│ Invalid version: 'zip-5'
╰─> Starting with pip 24.1, packages with invalid versions can not be processed.
```

This package has to be renamed
