### ISSUE TITLE
p7zip dependency on macOS

### ISSUE THREAD

**Issue by grosbecyk** [vapoursynth/vsrepo#241]
Running vsrepo.py withtout p7zip installed on mac gives this error:

```
Fetching: https://github.com/Stefan-Olt/vs-plugin-build/releases/download/vsplugin/com.holywu.curve/r3/darwin-aarch64/2024-09-30T20.52.46%2B00.00Z/Curve-r3-darwin-aarch64.zip
Traceback (most recent call last):
  File "/Users/admin/Git/vsrepo/./vsrepo.py", line 926, in <module>
    res = install_package(name)
  File "/Users/admin/Git/vsrepo/./vsrepo.py", line 718, in install_package
    fres = install_files(p)
  File "/Users/admin/Git/vsrepo/./vsrepo.py", line 682, in install_files
    result = subprocess.run([cmd7zip_path, "e", "-so", tfpath, fn_props[0]], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1966, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7z'

```

Installing p7zip using `brew install p7zip` fixes the issue.

Shouldn't this be documented?

Thanks

**Comment by Stefan-Olt** [comment]
When I adopted vsrepo for macOS/Linux I made the changes minimal, and as vsrepo uses 7z on Windows, it will use p7zip on macOS/Linux. How did you install vsrepo for macOS? Just cloning this repo?
It would be great if vsrepo could be for example included in brew, so you can install vapoursynth and vsrepo directly with brew and it will also install all dependencies.

**Comment by grosbecyk** [comment]
I installed by cloning and then running `python3 setup.py install`. Maybe we could just add the p7zip dependency in setup.py?  I agree that including vsrepo in brew would make things easier, especially considering that vsrepo is used "to make things easier". It's just a bit awkward to install on macOS/linux right now.
