### ISSUE TITLE
Upgrade error msg

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#28]
python .\vsrepo.py -p  upgrade tcanny
```
Fetching: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny/releases/download/r10/TCanny-r10.7z
Successfully installed TCanny r10
Traceback (most recent call last):
  File ".\vsrepo.py", line 335, in <module>
    res = upgrade_package(name, args.force)
  File ".\vsrepo.py", line 310, in upgrade_package
    inst[0] = 1
TypeError: 'tuple' object does not support item assignment
```

file was "installed" successfully

**Comment by myrsloik** [comment]
Doh, should be fixed now if you grab git
