### ISSUE TITLE
error during install 

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#43]
python.exe vsrepo.py -p upgrade-all -b vapoursynth64\plugins -s ..\Scripts
(used test11 from doom9)

```
Fetching: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3/releases/download/r3/EEDI3-r3.7z
Successfully installed EEDI3m r3
Fetching: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-SangNomMod/releases/download/v0.1-fix/sangnommod_v0.1.fix.zip
Successfully installed SangNomMod v0.1-fix
Fetching: https://api.github.com/repos/HomeOfVapourSynthEvolution/havsfunc/zipball/r30
Successfully installed havsfunc r30
Traceback (most recent call last):
  File "vsrepo.py", line 444, in <module>
    inst = upgrade_all_packages(args.force)
  File "vsrepo.py", line 363, in upgrade_all_packages
    for id in installed_ids:
RuntimeError: dictionary changed size during iteration
```

**Comment by myrsloik** [comment]
Doh, fixed now
