### ISSUE TITLE
TypeError during installation

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vsrepo#48]
```
...
Successfully installed AddGrain r6
Successfully installed HQDn3D r2
Traceback (most recent call last):
  File "C:\VS\vsrepo\vsrepo.py", line 429, in <module>
    res = install_package(name)
  File "C:\VS\vsrepo\vsrepo.py", line 324, in install_package
    res = install_package(dep)
  File "C:\VS\vsrepo\vsrepo.py", line 327, in install_package
    install_files(p)
  File "C:\VS\vsrepo\vsrepo.py", line 290, in install_files
    data = fetch_url_cached(url, p['name'] + ' ' + install_rel['version'])
  File "C:\VS\vsrepo\vsrepo.py", line 130, in fetch_url_cached
    data = fetch_ur1(url, desc)
  File "C:\VS\vsrepo\vsrepo.py", line 113, in fetch_ur1
    size = int(urlreq.headers['content-length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by myrsloik** [comment]
I think I know how to fix it but need to know the package to test it easily

**Comment by myrsloik** [comment]
Probably fixed now

**Comment by theChaosCoder** [comment]
Yep, no problems anymore
